# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Site settings
title:  Lewis-游亦有道
email: lewis.lufei@gmail.com
description: > # it is a blog,I use it to write some articles about game technology and share what I am intersted in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  1179432578

# Build settings
# highlighter: pygments
# markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]
# kramdown:
#   # input:         GFM
#   auto_ids:      true
#   auto_id_prefix: 'id-'
#   # footnote_nr:   1
#   # entity_output: as_char
#   # toc_levels:    1..6
#   smart_quotes:  lsquo,rsquo,ldquo,rdquo
  # use_coderay:   true

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style

# highlighter: Pygments
# pygment:  false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks"]
